on:
  push:
    branches:
    - main

jobs:
 e2e-tests:
  runs-on: windows-latest
  steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - uses: microsoft/playwright-github-action@v1

      - name: Install browser dependencies
        run: npx playwright install-deps chromium
          
      - name: Install dependencies and run tests
        run: npm install && npm test
      
      - name: Run Tests
        run: npm test