on:
  push:
    branches:
    - main
  pull_request:

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup
        uses: ./action/setup

      - name: Run Tests
        run: yarn test